version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./src/:/go/src
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: "linux/amd64"
    volumes:
      - ./mysql/save_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: idolm@ster
      MYSQL_USER: producer
      MYSQL_PASSWORD: producer_pass
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: producer
      PMA_PASSWORD: producer_pass
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
